name: Check

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Check
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # ktor's CIO engine isn't yet available on windows: once supported, we should add windows-latest to the following list
        os: [ ubuntu-latest, macOS-latest ]
    steps:

      # 1 - checkout repositories
      - name: Check out
        uses: actions/checkout@v3

      # 2 - setup cache and tools
      - name: Cached Konan
        uses: actions/cache@v2
        with:
          path: ~/.konan
          key: ${{ runner.os }}-konan-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-konan-
      - name: Cached Gradle
        uses: actions/cache@v3
        with:
          path: ~/.gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle-

      # 3 - tests
      - name: Build and test
        run: ./gradlew check
